name: Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install-deps:
    runs-on: liza
    steps:
      - name: Install system dependencies
        run: yum install -y python3 python3-pip
      - name: Install python dependencies
        run: python3 -m pip install -r requirements.txt

  execute:
    timeout-minutes: 1 #this should be enough to start, the bot itself detaches afterwards
    runs-on: liza 
    steps:
      - uses: actions/checkout@v2

      - name: Kill all running instances of the bot
        run: ps aux | grep bot.py | awk '{print $2}' | xargs kill -9 | true

      - name: Start the bot
        env:
          TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
        run: python3 main.py 
